import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
data = pd.read_csv(r'C:\Users\DELL\Desktop\data science DWIT\day3\day3task1\KathmanduHouse.csv')
data1 = pd.read_csv(r'C:\Users\DELL\Desktop\data science DWIT\day3\day3task1\LalitpurHouuse.csv')
# print(data.head())
# print(data.tail())
# print(data1.head())
# print(data1.tail())
price = np.array(data['Price'])
price1 = np.array(data['Price'])
print("********\n")
minimum = np.min(price)
print('The least amount of money to buy a house in kathmandu is',minimum)
print("********\n")
maximum = np.max(price)
print ('you should have maximum valued house in Kathmandu of RS',maximum)
print("********\n")
minimum1 = np.min(price)
print('The least amount of money to buy a house in lalitpur is',minimum1)
print("********\n")
maximum1 = np.max(price)
print ('you should have the maximum valued house of Lalitpur',maximum1)
print("********\n")
print("the all description of kathmandu data is\n",data.describe())
print("********\n")
print("the all description of Lalitpur data is\n",data1.describe())